### ISSUE TITLE
'bam2fastx --split-barcodes'  fails on command line v3.1.1

### ISSUE THREAD

**Issue by jrharting** [PacificBiosciences/SMRT-Link#39]
Demultiplexing bam files on the command line is not working due to a bug.  The bug does show up in smrtlink-beta running 3.1.1.  

    $ readlink -f $(which bam2fastq)
    /pbi/dept/secondary/builds/3.1.1/smrttools/fromsrc/linux/x86-64/libc-2.5/gcc-4.8.4/ubuntu-1404/182868/smrttools-fromsrc_3.1.1.182868.installdir/private/pacbio/bam2fastx/binwrap/bam2fastq
    $ bam2fastq --split-barcodes -o testOut/b2fq test.bam
    terminate called after throwing an instance of 'std::runtime_error'
      what():  barcode tag (bc) was requested but is missing
    Aborted (core dumped)

A workaround is vailable via a python script using pbcore.

**Comment by jrharting** [comment]
workaround in the repo: https://github.com/PacificBiosciences/SMRT-Link/blob/master/demultiplex.py

**Comment by AfterRain** [comment]
I am trying to get same data "Barcoded" fastq files. Is there any update for this task? Can I use this function?

**Comment by jrharting** [comment]
What version of smrt analysis do you have?

**Comment by AfterRain** [comment]
I currently have V3.1.1 version.

**Comment by jrharting** [comment]
Contrary to the (now edited) comment above, this bug is still in 3.1.1 (see the version of bam2fastq running in the error example).  The python workaround still works, and this bug is definitely fixed in the next release, 3.2 (due out soon).

**Comment by AfterRain** [comment]
@jrharting 
Thank you so much! 
If the new version is released, someone is going to inform the clients? 
We need to check data urgently So  I am trying to demultiplex bam files by barcodes refer to below  document 
(  https://github.com/PacificBiosciences/PacBioFileFormats/wiki/BAM-recipes#building-a-basecalls-bam-file-no-alignments ) 

 I almost get every barcoded fastq files, but all of the quality values are together with "!".  
So I tried to convert bam file to fastq without barcoding directly. 
However, It still shows same value like below,
![1](https://cloud.githubusercontent.com/assets/8130960/19399658/9858e61a-9220-11e6-9e54-21ca411841bd.JPG)

Do you know any reason why quality values are coming like this? 
Thank you!

**Comment by jrharting** [comment]
@AfterRain That is unexpected -- '!' is equivalent to 0.  What was the input?  What command did you use exactly to convert?

**Comment by AfterRain** [comment]
@jrharting 

First I generated barcoded subreads bam file using below command. 

$SMRTLINKAPI/bam2bam --barcodes /smrtlink/barcode/pacbio_384_symmetric_barcodes.fasta -o m.barcoded /rawsmrtlink/54090/r54090_20160916_181625/1_B01/m54090_160916_182103.subreads.bam  /rawsmrtlink/54090/r54090_20160916_181625/1_B01/m54090_160916_182103.scraps.bam

After that, I used below command to converting to fastq file.

bamtools convert -format fastq -in m.subreads.bam -out m.subreads.fastq

Then It will show like a screen shot. "!" value.

I tried to split bam files with each barcodes file and try it. And It is still the same.  
Please refer to below, 

samtools view -h m.barcoded.subreads.bam > m.barcoded.subreads.sam
cat m.barcoded.subreads.sam | egrep '^@|bc:B:S,370,370' | samtools view -bS - > S370--S370.sam
$SMRTLINKAPI/bamtools convert -format fastq -in S370--S370.sam -out S370--S370.fastq

Thank you,

**Comment by jrharting** [comment]
@AfterRain Those commands work on my end using a sample dataset.  Where did your original sequence data come from?  Are they converted RSII data or Sequel data?  What is the `qual` field in your pre-barcoding bam file?

$ samtools view unbarcoded.bam | cut -f11

**Comment by jrharting** [comment]
@AfterRain my apologies -- I can see from your comment that the data are sequel.  What is the output from

`$ samtools view /rawsmrtlink/54090/r54090_20160916_181625/1_B01/m54090_160916_182103.subreads.bam | cut -f11`

**Comment by AfterRain** [comment]
@jrharting I tried it with original bam file from the machine It shows all quality values with "!!!!!!!!!!!" Is it from machine side issue?

**Comment by jrharting** [comment]
@AfterRain This is in fact expected, as it turns out -- primary is currently not producing quality values per base on the Sequel instrument per the developers.  May I ask what your downstream analysis will be for these data?

**Comment by AfterRain** [comment]
@jrharting Currently, We are not using quality values yet. So It is no problem to generate the Consensus sequences. However, It looks like data has no quality so I though there is a possibility to create wrong sequences. And also, I feel data quality also a little bit bad. Is it no problem to use LAA2 program If data quality is not available from instruments? We are not able to test LAA2 yet because There is no input for barcoding in LAA2 protocol. In addition, We are planning to develop using Quality values for calculating base quality of Consensus sequence. Could you tell us is there any plan to create quality values in the future?
Could you tell us is there any plan to create quality values in the future? Thank you,

**Comment by jrharting** [comment]
@AfterRain The new Arrow model for consensus does not use the quality values the way that the Quiver model does (did).  LAA2, which uses Arrow in consensus, is fully operational on Sequel data even though the raw qual values are not reported as yet.  Consensus quality values from arrow *are* reported in the outputs.  Same goes for CCS2.  
If you are working with SMRT Link 3.1, then barcoding is possible for LAA2, it is just a separate protocol (named "Barcoding").  The Barcoding protocol will generate a new dataset with "(barcoded)" appended to the name of the original.  You can then select this barcoded dataset for input to LAA2.  In LAA2, I would recommend a minimum barcode filter of at least 45 (scale is 0-100).  If you have lots of data, you can push this up to 55-60.

There will be raw quality values generated in the future, but  do not currently know the exact timeline.

**Comment by AfterRain** [comment]
@jrharting Thank you so much this is really helpful since there are not so many documents for Smart link yet! As we mention, we are also not using a quality score yet to make consensus sequence, So It's not a problem. Could you tell me is there any reason you are choosing that algorithm instead of Quiver algorithm (using quality value)? Actually, we are thinking to analyze and make calculation logic together with QScore and provide consensus sequence quality value. But I am not so sure It is right direction or not. We are currently using RSII in the production and testing in the Sequel machine.

**Comment by jrharting** [comment]
@AfterRain You're welcome :).  The Arrow model is much improved over Quiver, and a lot of work by our statisticians has gone into improving it.  Additionally, it is easier to train, so that future improvements in terms of chemistry and other primary factors can be included in the model more easily.  Here is a link with some information:
https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/FAQ.rst
 Also here is more info about the overall PB consensus design   (some focus on CCS, but the model is essentially the same in LAA)
https://github.com/PacificBiosciences/unanimity/blob/master/doc/PBCCS.md

**Comment by AfterRain** [comment]
@jrharting thank you, and I will check it :) Currently, I am trying to generate barcodes throw smart link, But I am not able to find any score option for that. Could you tell me how I can set the barcode filtering option both for LAA2 throw smart link and throw command line for generating fastq file? Is there any documentation for that detail?

**Comment by jrharting** [comment]
@AfterRain The barcoding protocol in smrtlink does not do any filtering, by design.  It simply labels every row with a barcode and barcode quality tag (bc/bq) where possible (some rows come from sequencing holes where no adapter was identified, thus no barcode).  Filtering should occur in downstream analyses, like LAA2.  After you have barcoded your dataset and you are setting up your LAA2 analysis in smrtlink, click on 'Advanced Analysis Parameters' and you will find a place to input a minimum barcode filter:

![image](https://cloud.githubusercontent.com/assets/3595985/19456431/425d672e-9476-11e6-966c-39aaebef9302.png)

**Comment by jrharting** [comment]
More detailed documantation is coming!

To apply a filter on the command line, you will be able to use the `dataset filter` tool once the bug noted above is fixed:

`dataset filter input.subreadset.xml output.subreadset.xml 'bq>=45`

In the mean time, you can use bamtools:

`bamtools filter -in subreads.bam -out filtered.subreads.bam -tag "bq":">=45"`

Then convert the output to fastq using `bamtools convert` as above.

**Comment by AfterRain** [comment]
@jrharting This is great!
Thank u so much for your time I will follow up with this! have a nice day.

**Comment by AfterRain** [comment]
@jrharting I am sorry, I have one more issue. I am trimming sequences using bq >= 45, but It is too much trimming sequences. 
As is 9.6 GB To be 400MB. I think this score is not suitable for us or there is some problem on the barcoding. How can we calculate this barcode score? Is it the same concept as RS II? We are using Qscore 22 on the RS II. Example one sequence is "TCAGACGATGCGTCAT" I apologize If this dashboard is not for this kind of question. Just feel free to let me know I can file a case also! Thank you.

**Comment by jrharting** [comment]
@AfterRain My bad! The barcode quality scale in 3.1.1 is still 0-64, not 0-100 as it will be going forward starting from the next release to standardize the scale better (and hopefully avoid issue like this one).  The scaling is linear, so for your data you can use a filter at about 28.  Very sorry for the confusion -- we are really trying to fix that.

**Comment by AfterRain** [comment]
@jrharting No problem at all :) It is working fine for both! I am going to analyze results. 
Thank you so much for your time and help!

**Comment by alimayy** [comment]
Hi @jrharting (and @AfterRain)

I found the above correspondence very useful. I have a few comments and questions related to this topic, could you briefly comment on them?

- The number of reads I get per barcode when I follow the command-line "bam2bam && demultiplex.py" and "bam2bam && bamtools && samtools && cat && samtools" approaches are the same, which as far as I understand is expected. But when I use the SMRT link web portal for barcoding, I get considerably different number of reads per barcode. In SMRT link web interface (SMRT Analysis ->_barcoding_job_id_ -> Barcodes -> Barcodes), it says 

**Barcodes**
Barcode name | **Reads** | Bases
0--0 | **428764** | 1248488618
1--1 | **195423** | 512549883
2--2 | **533390** | 1463436753

"bam2bam && demultiplex.py" and "bam2bam && samtools && bamtools" give me
Barcode name | Reads
0--0 | **293255**
1--1 | **225998**
2--2 | **637326**

Any idea what might be causing this difference, or which method is more reliable? I used the "bamtools && samtools && cat && samtools" on the SMRT portal output and I indeed got 428k sequences. What might be the reason for this?

- The thread's title refers to the command line option failing with the error

> what(): barcode tag (bc) was requested but is missing

I get the same error using the SMRT link web interface when I try to run a `Convert BAM to FASTX` 
analysis on a <ID> (barcoded) dataset. 

From `/home/pacbio/smrt_root/userdata/jobs_root.local/000/000011/tasks/pbcoretools.tasks.bam2fastq_archive-0/stderr`:

```
Failed task pbcoretools.tasks.bam2fastq_archive exit code 250 in 4.52 sec (See file '/home/pacbio/smrt_root/userdata/jobs_root/000/000011/tasks/pbcoretools.tasks.bam2fastq_archive-0/stderr'.)
Extracted from stderr
Running task in /home/pacbio/smrt_root/userdata/jobs_root/000/000011/tasks/pbcoretools.tasks.bam2fastq_archive-0
terminate called after throwing an instance of 'std::runtime_error'
  what():  barcode tag (bc) was requested but is missing
Completed running <ResolvedToolContract id:pbcoretools.tasks.bam2fastq_archive > exitcode -6 in 2.48 sec.
```
So I guess the bug is not only limited to the command-line interface?

**Comment by jrharting** [comment]
Hi @alimayy,
That is correct -- the bam2bam tool only checks barcode sequences in one direction.  This is intended to improve calling accuracy by reducing the 'space of false positives' that is generated when looking at barcodes in both directions.  

The tool bam2bam is what is used by SMRTlink to demultiplex, so command line bugs are also UI bugs in most cases.

**Comment by alimayy** [comment]
@jrharting Thanks for the clarifications
